export const FACTS_IMAGE_ROOT = "assets/facts";

export const FACTS_STATE_IMAGE_OVERRIDES = Object.freeze({
  bayern: `${FACTS_IMAGE_ROOT}/states/bayern-facts.webp`,
});

export const TOURISM_LINKS = {
  germany: "https://www.germany.travel/",
  states: {
    "baden-wuerttemberg": "https://www.tourismus-bw.de/",
    "bayern": "https://www.bayern.by/",
    "berlin": "https://www.visitberlin.de/",
    "brandenburg": "https://www.reiseland-brandenburg.de/",
    "bremen": "https://www.bremen-tourism.de/",
    "hamburg": "https://www.hamburg-tourism.de/",
    "hessen": "https://www.hessen-tourismus.de/",
    "mecklenburg-vorpommern": "https://www.auf-nach-mv.de/",
    "niedersachsen": "https://www.reiseland-niedersachsen.de/",
    "nordrhein-westfalen": "https://www.nrw-tourismus.de/",
    "rheinland-pfalz": "https://www.rlp-tourismus.com/",
    "saarland": "https://www.urlaub.saarland/",
    "sachsen": "https://www.sachsen-tourismus.de/",
    "sachsen-anhalt": "https://www.sachsen-anhalt-tourismus.de/",
    "schleswig-holstein": "https://www.sh-tourismus.de/",
    "thueringen": "https://www.thueringen-entdecken.de/",
  },
  countries: {
    "frankreich": "https://www.france.fr/",
    "spanien": "https://www.spain.info/",
    "england": "https://www.visitengland.com/",
    "schweden": "https://visitsweden.com/",
    "polen": "https://www.polen.travel/de/",
    "oesterreich": "https://www.austria.info/",
    "ungarn": "https://visithungary.com/",
    "kroatien": "https://croatia.hr/",
    "bosnien-herzegowina": "https://www.tourismbih.com/",
    "serbien": "https://www.serbia.travel/en",
    "nordmazedonien": "https://northmacedonia-timeless.com/",
    "albanien": "https://albania.al/",
    "griechenland": "https://www.visitgreece.gr/",
    "bulgarien": "https://bulgariatravel.org/en/",
    "tuerkei": "https://goturkiye.com/",
    "rumaenien": "https://www.romania.travel/",
    "ukraine": "https://ukraine.ua/visit/",
    "russland": "https://visitrussia.org.uk/",
    "weissrussland": "https://www.belarus.by/en/travel/",
    "tschechien": "https://www.visitczechia.com/",
    "slowakei": "https://slovakia.travel/en",
    "slowenien": "https://www.slovenia.info/en",
    "italien": "https://www.italia.it/en",
    "niederlande": "https://www.holland.com/global/tourism/discover-the-netherlands.htm",
    "belgien": "https://visitbelgium.com/",
    "daenemark": "https://www.visitdenmark.com/",
    "finnland": "https://www.visitfinland.com/",
    "norwegen": "https://www.visitnorway.com/",
    "irland": "https://www.ireland.com/",
    "schweiz": "https://www.myswitzerland.com/",
    "vatikanstadt": "https://www.vaticanstate.va/en/",
    "portugal": "https://www.visitportugal.com/",
    "montenegro": "https://www.montenegro.travel/en",
    "luxemburg": "https://www.visitluxembourg.com/",
    "liechtenstein": "https://tourismus.li/en/",
    "andorra": "https://visitandorra.com/en/",
    "kanada": "https://travel.destinationcanada.com/",
    "usa": "https://www.visittheusa.com/",
    "china": "https://www.visitchina.com/",
    "brasilien": "https://www.visitbrasil.com/",
    "australien": "https://www.australia.com/",
    "indien": "https://www.incredibleindia.gov.in/",
    "argentinien": "https://www.argentina.travel/en",
    "algerien": "https://www.algeria.com/",
    "mexiko": "https://www.visitmexico.com/en/",
    "indonesien": "https://www.indonesia.travel/gb/en/home",
    "japan": "https://www.japan.travel/en/",
    "suedkorea": "https://english.visitkorea.or.kr/",
    "pakistan": "https://www.tourism.gov.pk/",
    "bangladesch": "https://bangladeshtourismboard.gov.bd/",
    "nigeria": "https://tourism.gov.ng/",
    "aethiopien": "https://visitethiopia.et/",
    "aegypten": "https://www.experienceegypt.eg/",
    "suedafrika": "https://www.southafrica.net/gl/en/travel",
    "kasachstan": "https://kazakhstan.travel/en",
    "peru": "https://www.peru.travel/en",
    "kolumbien": "https://colombia.travel/en",
    "chile": "https://www.chile.travel/en/",
    "venezuela": "https://www.venezuelatuya.com/",
    "neuseeland": "https://www.newzealand.com/int/",
    "thailand": "https://www.tourismthailand.org/home",
    "vietnam": "https://vietnam.travel/",
  },
};

export const OFFICIAL_LINKS = {
  germany: "https://www.deutschland.de/",
  states: {
    "baden-wuerttemberg": "https://www.baden-wuerttemberg.de/",
    "bayern": "https://www.bayern.de/",
    "berlin": "https://www.berlin.de/",
    "brandenburg": "https://www.brandenburg.de/",
    "bremen": "https://www.bremen.de/",
    "hamburg": "https://www.hamburg.de/",
    "hessen": "https://www.hessen.de/",
    "mecklenburg-vorpommern": "https://www.regierung-mv.de/",
    "niedersachsen": "https://www.niedersachsen.de/",
    "nordrhein-westfalen": "https://www.land.nrw/",
    "rheinland-pfalz": "https://www.rlp.de/",
    "saarland": "https://www.saarland.de/",
    "sachsen": "https://www.sachsen.de/",
    "sachsen-anhalt": "https://www.sachsen-anhalt.de/",
    "schleswig-holstein": "https://www.schleswig-holstein.de/",
    "thueringen": "https://thueringen.de/",
  },
  countries: {
    "frankreich": "https://www.gouvernement.fr/en",
    "spanien": "https://administracion.gob.es/",
    "england": "https://www.gov.uk/",
    "schweden": "https://sweden.se/",
    "polen": "https://www.gov.pl/web/gov",
    "oesterreich": "https://www.oesterreich.gv.at/en/",
    "ungarn": "https://abouthungary.hu/",
    "kroatien": "https://vlada.gov.hr/?lang=en",
    "bosnien-herzegowina": "https://bih.gov.ba/?lang=en",
    "serbien": "https://www.srbija.gov.rs/?lang=en-US",
    "nordmazedonien": "https://vlada.mk/?ln=en-gb",
    "albanien": "https://albania.al/",
    "griechenland": "https://www.gov.gr/en/",
    "bulgarien": "https://www.government.bg/en",
    "tuerkei": "https://www.turkiye.gov.tr/",
    "rumaenien": "https://www.romania.gov.ro/en/",
    "ukraine": "https://www.ukraine.ua/",
    "russland": "https://government.ru/en/",
    "weissrussland": "https://www.belarus.by/en/",
    "tschechien": "https://www.czech.cz/en/",
    "slowakei": "https://welcometoslovakia.gov.sk/",
    "slowenien": "https://slovenia.si/",
    "italien": "https://www.governo.it/en",
    "niederlande": "https://www.government.nl/",
    "belgien": "https://www.belgium.be/en",
    "daenemark": "https://denmark.dk/",
    "finnland": "https://finland.fi/",
    "norwegen": "https://www.norge.no/en",
    "irland": "https://www.gov.ie/en/",
    "schweiz": "https://www.admin.ch/gov/en/start.html",
    "vatikanstadt": "https://www.vaticanstate.va/en/",
    "portugal": "https://www.portugal.gov.pt/en/gc23",
    "montenegro": "https://www.gov.me/en",
    "luxemburg": "https://gouvernement.lu/en.html",
    "liechtenstein": "https://www.liechtenstein.li/en/",
    "andorra": "https://www.govern.ad/en/",
    "kanada": "https://www.canada.ca/en.html",
    "usa": "https://www.usa.gov/",
    "china": "https://english.www.gov.cn/",
    "brasilien": "https://www.gov.br/planalto/en",
    "australien": "https://www.australia.gov.au/",
    "indien": "https://www.india.gov.in/",
    "argentinien": "https://www.argentina.gob.ar/",
    "algerien": "https://www.interieur.gov.dz/",
    "dr-kongo": "https://www.primature.gouv.cd/",
    "saudi-arabien": "https://www.my.gov.sa/wps/portal/snp/main",
    "mexiko": "https://www.gob.mx/",
    "indonesien": "https://indonesia.go.id/",
    "sudan": "https://www.sudan.gov.sd/",
    "libyen": "https://government.gov.ly/",
    "iran": "https://en.irna.ir/",
    "mongolei": "https://mongolia.gov.mn/en/",
    "japan": "https://www.japan.go.jp/",
    "suedkorea": "https://www.korea.net/",
    "pakistan": "https://www.pakistan.gov.pk/",
    "bangladesch": "https://bangladesh.gov.bd/index.php",
    "nigeria": "https://statehouse.gov.ng/",
    "aethiopien": "https://pmo.gov.et/",
    "aegypten": "https://www.sis.gov.eg/",
    "suedafrika": "https://www.gov.za/",
    "kasachstan": "https://www.gov.kz/memleket/entities?lang=en",
    "peru": "https://www.gob.pe/en/",
    "kolumbien": "https://www.gov.co/",
    "chile": "https://www.gob.cl/en/",
    "venezuela": "https://mppre.gob.ve/en/",
    "neuseeland": "https://www.govt.nz/",
    "thailand": "https://www.thaigov.go.th/",
    "vietnam": "https://en.vietnamplus.vn/",
  },
  world: "https://www.un.org/en/",
};

export const EUROPE_FLAG_IMAGE = `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 150 90" role="img" aria-label="Flagge Europas">
    <rect width="150" height="90" fill="#003399"/>
    <g fill="#ffcc00">
      <circle cx="75" cy="19" r="3.2"/>
      <circle cx="89" cy="22.8" r="3.2"/>
      <circle cx="99.2" cy="33" r="3.2"/>
      <circle cx="103" cy="45" r="3.2"/>
      <circle cx="99.2" cy="57" r="3.2"/>
      <circle cx="89" cy="67.2" r="3.2"/>
      <circle cx="75" cy="71" r="3.2"/>
      <circle cx="61" cy="67.2" r="3.2"/>
      <circle cx="50.8" cy="57" r="3.2"/>
      <circle cx="47" cy="45" r="3.2"/>
      <circle cx="50.8" cy="33" r="3.2"/>
      <circle cx="61" cy="22.8" r="3.2"/>
    </g>
  </svg>`
)}`;

export const STATE_NOTABLE_PEOPLE = {
  "baden-wuerttemberg": {
    science: ["Albert Einstein", "Johannes Kepler", "Carl Benz"],
    politics: ["Theodor Heuss", "Carlo Schmid", "Winfried Kretschmann"],
    art: ["Friedrich Schiller", "Hermann Hesse", "Otto Dix"],
    engineering: ["Carl Benz", "Gottlieb Daimler"],
  },
  bayern: {
    science: ["Werner Heisenberg", "Carl von Linde", "Rudolf Diesel"],
    politics: ["Franz Josef Strauss", "Kurt Eisner", "Markus Soeder"],
    art: ["Richard Wagner", "Franz Marc", "Oskar Maria Graf"],
    engineering: ["Rudolf Diesel", "Oskar von Miller"],
  },
  berlin: {
    science: ["Albert Einstein", "Max Planck", "Rudolf Virchow"],
    politics: ["Willy Brandt", "Angela Merkel", "Walter Rathenau"],
    art: ["Marlene Dietrich", "Käthe Kollwitz", "Bertolt Brecht"],
    engineering: ["Werner von Siemens", "Konrad Zuse"],
  },
  brandenburg: {
    science: ["Hermann von Helmholtz", "Hasso Plattner", "Karl Foerster"],
    politics: ["Matthias Platzeck", "Dietmar Woidke", "Manfred Stolpe"],
    art: ["Heinrich von Kleist", "Theodor Fontane", "Wolfgang Joop"],
    engineering: ["Otto Lilienthal", "Hasso Plattner"],
  },
  bremen: {
    science: ["Heinrich Wilhelm Olbers", "Adolf Bastian"],
    politics: ["Hans Koschnick", "Henning Scherf", "Karl Carstens"],
    art: ["Paula Modersohn-Becker", "Loriot", "Wilhelm Wagenfeld"],
    engineering: ["Ludwig Franzius", "Wilhelm Wagenfeld"],
  },
  hamburg: {
    science: ["Otto Stern", "Ernst Ruska", "Klaus Hasselmann"],
    politics: ["Helmut Schmidt", "Olaf Scholz", "Peter Tschentscher"],
    art: ["Johannes Brahms", "Udo Lindenberg", "Wolfgang Borchert"],
    engineering: ["Fritz Schumacher", "Ernst Ruska"],
  },
  hessen: {
    science: ["Paul Ehrlich", "Robert Bunsen", "Otto Hahn"],
    politics: ["Joschka Fischer", "Georg-August Zinn", "Volker Bouffier"],
    art: ["Johann Wolfgang von Goethe", "Brüder Grimm", "Anne Frank"],
    engineering: ["Konrad Zuse", "Ferdinand Braun"],
  },
  "mecklenburg-vorpommern": {
    science: ["Heinrich Schliemann", "Albrecht Kossel", "Otto Lilienthal"],
    politics: ["Angela Merkel", "Manuela Schwesig", "Joachim Gauck"],
    art: ["Caspar David Friedrich", "Fritz Reuter", "Uwe Johnson"],
    engineering: ["Otto Lilienthal", "Ernst Ruska"],
  },
  niedersachsen: {
    science: ["Carl Friedrich Gauss", "Wilhelm Weber", "David Hilbert"],
    politics: ["Gerhard Schröder", "Christian Wulff", "Ernst Albrecht"],
    art: ["Wilhelm Busch", "Kurt Schwitters", "Niki de Saint Phalle"],
    engineering: ["Heinrich Büssing", "Konrad Zuse"],
  },
  "nordrhein-westfalen": {
    science: ["Harald zur Hausen", "Max Born", "Julius Plücker"],
    politics: ["Konrad Adenauer", "Johannes Rau", "Armin Laschet"],
    art: ["Ludwig van Beethoven", "Heinrich Böll", "Joseph Beuys"],
    engineering: ["Friedrich Alfred Krupp", "Carl Bosch"],
  },
  "rheinland-pfalz": {
    science: ["Johannes Gutenberg", "Hermann Staudinger", "Julius Richard Petri"],
    politics: ["Helmut Kohl", "Malu Dreyer", "Kurt Beck"],
    art: ["Hildegard von Bingen", "Max Slevogt", "Thomas Nast"],
    engineering: ["Nikolaus Otto", "Karlheinz Brandenburg"],
  },
  saarland: {
    science: ["Peter Grünberg", "Wolfgang Wahlster"],
    politics: ["Oskar Lafontaine", "Heiko Maas", "Annegret Kramp-Karrenbauer"],
    art: ["Max Ophüls", "Nicole", "Gerd Dudenhöffer"],
    engineering: ["Hermann Röchling", "Wolfgang Wahlster"],
  },
  sachsen: {
    science: ["Gottfried Wilhelm Leibniz", "Wilhelm Ostwald", "Manfred von Ardenne"],
    politics: ["August Bebel", "Kurt Biedenkopf", "Stanislaw Tillich"],
    art: ["Richard Wagner", "Erich Kästner", "Caspar David Friedrich"],
    engineering: ["August Horch", "Manfred von Ardenne"],
  },
  "sachsen-anhalt": {
    science: ["Otto von Guericke", "Dorothea Erxleben", "Georg Cantor"],
    politics: ["Hans-Dietrich Genscher", "Reiner Haseloff", "Wolfgang Böhmer"],
    art: ["Georg Friedrich Händel", "Lyonel Feininger", "Johann Joachim Winckelmann"],
    engineering: ["Hugo Junkers", "Otto von Guericke"],
  },
  "schleswig-holstein": {
    science: ["Max Planck", "Otto Diels", "Ferdinand Tönnies"],
    politics: ["Willy Brandt", "Heide Simonis", "Daniel Günther"],
    art: ["Thomas Mann", "Günter Grass", "Emil Nolde"],
    engineering: ["Ernst Barlach", "Otto Diels"],
  },
  thueringen: {
    science: ["Carl Zeiss", "Ernst Abbe", "Johann Wolfgang Döbereiner"],
    politics: ["Bodo Ramelow", "Christine Lieberknecht", "Bernhard Vogel"],
    art: ["Johann Sebastian Bach", "Johann Wolfgang von Goethe", "Friedrich Schiller"],
    engineering: ["Carl Zeiss", "Ernst Abbe"],
  },
};
